openapi: "3.0.3"
info:
  title: "11"
  description: ""
  version: "asdfgh"
tags: []
paths:
  /test:
    get:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
components:
  schemas: {}
