openapi: "3.0.0"
info:
  title: ""
  description: ""
  version: "1"
tags: []
paths:
  /user:
    get:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                example:
                  abcd:
                    name: "jon"
components:
  schemas: {}
