swagger: "2.0"
info:
  title: "Test2"
  description: "desc"
  version: "2"
paths:
  /test2:
    get:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
          examples:
            application/json:
              msg: "success"
      produces:
        - "application/json"
    post:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
          examples:
            application/json:
              msg: "success"
      produces:
        - "application/json"
      consumes:
        - "application/json"
    put:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
          examples:
            application/json:
              msg: "success"
      produces:
        - "application/json"
      consumes:
        - "application/json"
    delete:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
          examples:
            application/json:
              msg: "success"
      produces:
        - "application/json"
    patch:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          schema:
            type: "object"
            properties:
              msg:
                type: "string"
          examples:
            application/json:
              msg: "success"
      produces:
        - "application/json"
      consumes:
        - "application/json"
