openapi: "3.0.3"
info:
  title: "Test3.0"
  description: "desc"
  version: "1"
paths:
  /test3:
    get:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
    put:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
    delete:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
    post:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
    patch:
      summary: ""
      description: ""
      parameters: []
      responses:
        200:
          description: "success response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
              example:
                - msg: "success"
components:
  schemas:
    testschema:
      type: "object"
      description: ""
